[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "."
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Optional: Set up redirects or headers if needed
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
